# fly.toml app configuration file generated for rough-butterfly-4092 on 2023-11-01T02:08:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-butterfly-4092"
primary_region = "bos"

[build]

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
